<script>
  import { onMount } from "svelte";
  import { genres, specificMovie } from "../../stores";
  import Stars from "../UI/Stars.svelte";

  export let id = "";
  export let src = "";
  export let title = "";
  export let genre_ids = "";
  export let release_date = "";
  export let vote_average = "";
  export let overview = "";
  export let backdrop_path = "";
  export let original_language = "";

  $: genres_names = "";
  onMount(async () => {
    let gen = await $genres;
    genres_names = await gen
      .filter(x => genre_ids.includes(x.id))
      .map(x => x.name)
      .join(", ");
  });
</script>

<style>
  a {
    text-decoration: none;
  }
  .card-body {
    background-color: black;
    color: white;
  }

  .slide-top {
    -webkit-animation: slide-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
    animation: slide-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  }
  /* ----------------------------------------------
 * Generated by Animista on 2020-10-17 12:50:56
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation slide-top
 * ----------------------------------------
 */
  @-webkit-keyframes slide-top {
    0% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
    }
    100% {
      -webkit-transform: translateY(-100px);
      transform: translateY(-100px);
    }
  }
  @keyframes slide-top {
    0% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
    }
    100% {
      -webkit-transform: translateY(-100px);
      transform: translateY(-100px);
    }
  }
</style>

<a href={`/movie/${id}`}>
  <div class="card card-body flex-fill slide-top">
    <img class="card-img-top" {src} alt="Card image cap" />
    <div class="card-body">
      <h5 id="card-title">{title.trim()}</h5>
      <p>
        <small class="card-text">{genres_names}</small>
      </p>
      <p>
        <small class="card-text">
          Vote Average: {vote_average.slice(0, -1)}
        </small>
      </p>
      <p>

        <small class="text-muted">Release Date: {release_date}</small>

      </p>

    </div>
    <div class="card-footer">
      <br />
    </div>
  </div>
</a>
