<script>
  import { API_KEY } from "../../stores";
  import { onMount } from "svelte";
  import Actors from "./Actors.svelte";
  export let params;

  let urlMovie = `https://api.themoviedb.org/3/movie/${params.id}?api_key=${API_KEY}&language=en-US`;
  let imageUrl = "https://image.tmdb.org/t/p/w500";
  let urlActors = `https://api.themoviedb.org/3/movie/${params.id}/casts?api_key=${API_KEY}`;

  $: movie = "";
  $: actors = "";
  $: console.log(actors);
  $: src = movie ? `${imageUrl}${movie.poster_path}` : "";

  let fetchUrl = async (url, kind) => {
    let res = await fetch(url);
    kind = await res.json();
    return kind;
  };

  onMount(async () => {
    movie = await fetchUrl(urlMovie, movie);
    actors = await fetchUrl(urlActors, actors);
  });
</script>

<style>
  .movie-container {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
  }
  .box {
    background-color: black;
    color: white;
  }

  .shadow-pop-tr {
    -webkit-animation: shadow-pop-tr 0.3s cubic-bezier(0.47, 0, 0.745, 0.715)
      both;
    animation: shadow-pop-tr 0.3s cubic-bezier(0.47, 0, 0.745, 0.715) both;
  }
  /* ----------------------------------------------
 * Generated by Animista on 2020-10-17 12:58:0
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation shadow-pop-tr
 * ----------------------------------------
 */
  @-webkit-keyframes shadow-pop-tr {
    0% {
      -webkit-box-shadow: 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e,
        0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e;
      box-shadow: 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e,
        0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e;
      -webkit-transform: translateX(0) translateY(0);
      transform: translateX(0) translateY(0);
    }
    100% {
      -webkit-box-shadow: 1px -1px #3e3e3e, 2px -2px #3e3e3e, 3px -3px #3e3e3e,
        4px -4px #3e3e3e, 5px -5px #3e3e3e, 6px -6px #3e3e3e, 7px -7px #3e3e3e,
        8px -8px #3e3e3e;
      box-shadow: 1px -1px #3e3e3e, 2px -2px #3e3e3e, 3px -3px #3e3e3e,
        4px -4px #3e3e3e, 5px -5px #3e3e3e, 6px -6px #3e3e3e, 7px -7px #3e3e3e,
        8px -8px #3e3e3e;
      -webkit-transform: translateX(-8px) translateY(8px);
      transform: translateX(-8px) translateY(8px);
    }
  }
  @keyframes shadow-pop-tr {
    0% {
      -webkit-box-shadow: 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e,
        0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e;
      box-shadow: 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e,
        0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e, 0 0 #3e3e3e;
      -webkit-transform: translateX(0) translateY(0);
      transform: translateX(0) translateY(0);
    }
    100% {
      -webkit-box-shadow: 1px -1px #3e3e3e, 2px -2px #3e3e3e, 3px -3px #3e3e3e,
        4px -4px #3e3e3e, 5px -5px #3e3e3e, 6px -6px #3e3e3e, 7px -7px #3e3e3e,
        8px -8px #3e3e3e;
      box-shadow: 1px -1px #3e3e3e, 2px -2px #3e3e3e, 3px -3px #3e3e3e,
        4px -4px #3e3e3e, 5px -5px #3e3e3e, 6px -6px #3e3e3e, 7px -7px #3e3e3e,
        8px -8px #3e3e3e;
      -webkit-transform: translateX(-8px) translateY(8px);
      transform: translateX(-8px) translateY(8px);
    }
  }
</style>

<div class="movie-container container-fluid">
  <a href={`/`} class="my-2">
    <button class="btn btn-success">Back To Home Page</button>
  </a>
  {#if movie}
    <div class="card box shadow-pop-tr" style="max-width: 60vw;">
      <div class="row no-gutters">
        <div class="col-md-4">
          <img {src} class="card-img" alt="movie-img" />
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">{movie.title}</h5>
            <p class="card-text">{movie.overview}</p>
            <p class="card-text text-muted">
              Vote Average: {movie.vote_average}
            </p>
            <p class="card-text text-muted">
              Realese Date: {movie.release_date}
            </p>
          </div>
        </div>
      </div>
    </div>
  {/if}
</div>
{#if actors}
  <Actors {actors} {imageUrl} />
{/if}
